name: lnp_mod
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=24.0
  
  # CUDA Dependencies
  - cudatoolkit=12.1
  - cudnn=8.9.2
  
  # Core ML/DL
  - pytorch>=2.3.1
  - torchvision>=0.18.1
  - opencv-python>=4.10.0
  - numpy>=1.26.4
  - scipy>=1.13.1
  - monai>=1.3.2
  
  # Data Processing
  - pandas>=2.2.2
  - shapely>=2.0.5
  - setuptools>=69.5.1
  
  # Visualization
  - matplotlib>=3.9.1
  - seaborn>=0.13.2
  
  # Development
  - pytest>=7.4.0
  - black>=23.3.0
  - flake8>=6.0.0
  - typing-extensions>=4.12.0
  
  - pip:
    - ultralytics>=8.2.58
    - pycocotools>=2.0.8
    - supervision>=0.22.0
    - plotly>=5.18.0
    - gdown>=5.2.0
    - kaleido>=0.2.1
    - openpyxl>=3.1.2
    - tqdm>=4.66.4
    - pyyaml>=6.0.1
    - albumentations>=1.3.1